- hosts: localhost
  become: yes
  vars: 
    ansible_user: parth
  tasks:
    - name: Update system
      pacman:
        update_cache: yes
        upgrade: yes

  roles:
    - base
    - yay
    - dotfiles
